apiVersion: 1

datasources:
  - name: InfluxDB-iRacing
    uid: iracing-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: false
    jsonData:
      version: Flux
      organization: iracing
      defaultBucket: telemetry
      tlsSkipVerify: true
    secureJsonData:
      token: iracing-super-token
